### ISSUE TITLE
DataCleaning - removing columns with more that 30 % missing

### ISSUE THREAD

**Issue by poornimaarunp** [poornimaarunp/EDAGroupCaseStudy#1]
deleting columns with more than 30% missing

df_loan_new = df_loan_new.drop('desc', axis=1)
df_loan_new = df_loan_new.drop('mths_since_last_delinq', axis=1)
df_loan_new = df_loan_new.drop('mths_since_last_record', axis=1)
df_loan_new = df_loan_new.drop('next_pymnt_d', axis=1)

@Divyauk, I feel we can keep desc column and fillna with new category as 'NotProvided'
I am yet to see the other columns, can we reverify if we have to delete the columns?

**Comment by Divyauk** [comment]
Desc was more of text data . We have come to that stage to analyze text. Hence I removed. 

But sure if you really feel there is a need we can keep the columns. That is why it is a group case study. We can all put in our views

**Comment by poornimaarunp** [comment]
Thanks Divya, i thought we can convert that column to 'description provided' and 'Not Provided'. will it make sense?

**Comment by Divyauk** [comment]
Ok. That is a good point. We can do that

**Comment by poornimaarunp** [comment]
all null values in next_pymnt_d fall under 'Fully Paid' or 'Charged Off' under loan_status column. we have to keep this column to analyze next_pymnt_d  on other loan statuses

**Comment by poornimaarunp** [comment]
Similarly.. for rows that has 'pub_rec' as value '0', values are null in 'mths_since_last_record'
pub_rec --> Number of derogatory public records
mths_since_last_record --> The number of months since the last public record.
so it is obvious that is pub_rec==0, then there will be no value for mths_since_last_record. 

We need to keep this column to analyze for rows against 'pub_rec' that has values other than zero

**Comment by Divyauk** [comment]
ok. sure .Lets keep it then.

**Comment by poornimaarunp** [comment]
I have fixed this now
