### ISSUE TITLE
Some columns that have only values 

### ISSUE THREAD

**Issue by poornimaarunp** [poornimaarunp/EDAGroupCaseStudy#2]
pymnt_plan - has only 'n'
initial_list_status - has only 'f'
collections_12_mths_ex_med - has only '0.0'
policy_code - has only '1'
application_type - has only 'INDIVIDUAL'
acc_now_delinq - has only '0'
chargeoff_within_12_mths - has only '0.0'
delinq_amnt - has only '0'
tax_liens - has only '0.0'

@Divyauk, Do we have to keep these columns in the dataset?

**Comment by Divyauk** [comment]
We can remove these columns

**Comment by poornimaarunp** [comment]
I have fixed this now
